### ISSUE TITLE
fairseq

### ISSUE THREAD

**Issue by beijita-yegucheng** [nii-yamagishilab/project-NN-Pytorch-scripts#28]
Is fairseq version 0.10.2 used? When I run bash 00_ demo. sh model-W2V-XLSR-ft-GF/config_ train_ Asvspoof2019 times error：Traceback (most recent call last):
  File "main.py", line 211, in <module>
    main()
  File "main.py", line 191, in main
    model = prj_model.Model(test_set.get_in_dim(), \
  File "/home/hcl/ASVspoof_code/project-NN-Pytorch-scripts-master/project/07-asvspoof-ssl/model-W2V-XLSR-ft-GF/config_train_asvspoof2019/01/model.py", line 197, in __init__
    self.m_ssl = SSLModel(ssl_path, ssl_orig_output_dim)
  File "/home/hcl/ASVspoof_code/project-NN-Pytorch-scripts-master/project/07-asvspoof-ssl/model-W2V-XLSR-ft-GF/config_train_asvspoof2019/01/model.py", line 44, in __init__
    model, _, _ = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "/home/hcl/anaconda3/envs/torch1.6/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/hcl/anaconda3/envs/torch1.6/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/hcl/anaconda3/envs/torch1.6/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

**Comment by TonyWangX** [comment]
Hello, 

Sorry for the inconvenience.

Could you try to install the fairseq using:
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/master/env-fs-install.sh

It is a specific version on github, not 0.10.2 on pip.
