### ISSUE TITLE
about 08-asvspoof-activelearn

### ISSUE THREAD

**Issue by Tianming40** [nii-yamagishilab/project-NN-Pytorch-scripts#58]
Dear author,

when I tried to run the bash script in the 08 project, I saw the following error in the training log.
```
(pytorch-1.7) ming@LAPTOP-EMOK5QV6:/mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn$ bash 00_demo.sh model-AL-NegE config_AL_train_toyset 01

=======================================================
Step1. Preparation: load environment and get toy data
Conda environment fairseq-pip2 has been installed

=======================================================

=======================================================
Step3. training on toy set
bash 01_train.sh 01 config_AL_train_toyset model-AL-NegE/config_AL_train_toyset/01 16 5 2 0.000001 /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt
cd model-AL-NegE/config_AL_train_toyset/01
Training starts
Please monitor the log trainig: /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train

python main.py --model-forward-with-file-name --num-workers 4 --epochs 2 --no-best-epochs 100 --batch-size 16 --lr 0.000001 --seed 01 --module-config config_AL_train_toyset --active-learning-cycle-num 5 --active-learning-new-sample-per-cycle 16 --trained-model /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt >log_train 2>log_train_err
Training process finished
Trainig log has been written to /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train

=======================================================
Step4. score the toy data set
ls: cannot access 'model-AL-NegE/config_AL_train_toyset/01/trained_network*.pt': No such file or directory
(pytorch-1.7) ming@LAPTOP-EMOK5QV6:/mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn$ bash 00_demo.sh model-AL-NegE config_AL_train_toyset 01

=======================================================
Step1. Preparation: load environment and get toy data
Conda environment fairseq-pip2 has been installed

=======================================================

=======================================================
Step3. training on toy set
bash 01_train.sh 01 config_AL_train_toyset model-AL-NegE/config_AL_train_toyset/01 16 5 2 0.000001 /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt
cd model-AL-NegE/config_AL_train_toyset/01
Training starts
Please monitor the log trainig: /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train

python main.py --model-forward-with-file-name --num-workers 4 --epochs 2 --no-best-epochs 100 --batch-size 16 --lr 0.000001 --seed 01 --module-config config_AL_train_toyset --active-learning-cycle-num 5 --active-learning-new-sample-per-cycle 16 --trained-model /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt >log_train 2>log_train_err
Training process finished
Trainig log has been written to /mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train

=======================================================
Step4. score the toy data set
ls: cannot access 'model-AL-NegE/config_AL_train_toyset/01/trained_network*.pt': No such file or directory
```
in /08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train_err
```
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    main()
  File "main.py", line 162, in main
    model = prj_model.Model(trn_set.get_in_dim(), \
  File "/mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/model.py", line 292, in __init__
    self.m_front_end = FrontEnd(self.v_feat_dim,
  File "/mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/model.py", line 109, in __init__
    self.ssl_model = SSLModel(mpath, ssl_out_dim)
  File "/mnt/d/UNI/IFM/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/model.py", line 56, in __init__
    md, _, _ = fq.checkpoint_utils.load_model_ensemble_and_task([mpath])
AttributeError: module 'fairseq' has no attribute 'checkpoint_utils'
```
 I want to know why? And I would like to ask how to use the pre-trained model in the downloaded folder project08-seed-model.tar to evaluate the wild data set?It would be great if you could offer some advice, I look forward to hearing from you. have a beautiful day

Best regards,
Ming

**Comment by TonyWangX** [comment]
@Tianming40 Sorry for the late reply. It is a busy period for paper submission.


>AttributeError: module 'fairseq' has no attribute 'checkpoint_utils'
This looks like an issue with fairseq installation.

Could you check the version of fairseq? 
```bash
(fairseq-pip2) $: python -c "import fairseq;print(fairseq.__version__)"
1.0.0a0+862efab
```

Did you install the requirement using https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/master/env-fs-install.sh?  The fairseq I used was from their git repo main branch. I have to specify the commit ID in order to get the correct version. Otherwise, the latest version would work.


I used another server and retried the script. It worked fine for me. 
Part of the log looks like:
```bash
bash 00_demo.sh model-AL-NegE config_AL_train_toyset 01

=======================================================
Step1. Preparation: load environment and get toy data

EnvironmentNameNotFound: Could not find conda environment: fairseq-pip2
You can list all discoverable environments with `conda info --envs`.


Install conda environment fairseq-pip2
Channels:
 - defaults
Platform: linux-64
...
...
...
Installing collected packages: bitarray, antlr4-python3-runtime, zipp, tqdm, tabulate, regex, PyYAML, pycparser, portalocker, lxml, cython, colorama, sacrebleu, omegaconf, importlib-resources, cffi, hydra-core, fairseq
Successfully installed PyYAML-6.0.1 antlr4-python3-runtime-4.8 bitarray-2.9.2 cffi-1.16.0 colorama-0.4.6 cython-3.0.8 fairseq-1.0.0a0+862efab hydra-core-1.0.7 importlib-resources-6.1.1 lxml-5.1.0 omegaconf-2.0.6 portalocker-2.8.2 pycparser-2.21 regex-2023.12.25 sacrebleu-2.4.0 tabulate-0.9.0 tqdm-4.66.2 zipp-3.17.0
Collecting pandas==1.4.3
  Downloading pandas-1.4.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 125.2 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.1 (from pandas==1.4.3)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas==1.4.3)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy>=1.18.5 in /home/acb10781lt/TOOL/pydev/miniconda3/envs/fairseq-pip2/lib/python3.8/site-packages (from pandas==1.4.3) (1.21.2)
Collecting six>=1.5 (from python-dateutil>=2.8.1->pandas==1.4.3)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: pytz, six, python-dateutil, pandas
Successfully installed pandas-1.4.3 python-dateutil-2.8.2 pytz-2024.1 six-1.16.0
...
...
...
=======================================================
Download and untar the toy data set
project-04-toy_exam 100%[==================>]
...
...
...
=======================================================
Step3. training on toy set
bash 01_train.sh 01 config_AL_train_toyset model-AL-NegE/config_AL_train_toyset/01 16 5 2 0.000001 /groups/gcf51224/wang/WORK/temp/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt
cd model-AL-NegE/config_AL_train_toyset/01
Training starts
Please monitor the log trainig: /groups/gcf51224/wang/WORK/temp/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/model-AL-NegE/config_AL_train_toyset/01/log_train

python main.py --model-forward-with-file-name --num-workers 4 --epochs 2 --no-best-epochs 100 --batch-size 16 --lr 0.000001 --seed 01 --module-config config_AL_train_toyset --active-learning-cycle-num 5 --active-learning-new-sample-per-cycle 16 --trained-model /groups/gcf51224/wang/WORK/temp/project-NN-Pytorch-scripts/project/08-asvspoof-activelearn/seed_model/w2v-ft-gf_trained_network.pt >log_train 2>log_train_err
...
...
...
```

The log_train_err looks like:
```bash
Active learning cycle 0, add samples: 98,LA_T_7422011,0,45646,0;15,LA_T_1870524,0,43190,0;12,LA_T_1653822,1,9756,64000;91,LA_T_7223887,0,40210,0;7,LA_T_1518499,0,29284,0;37,LA_T_3189628,1,15851,64000;78,LA_T_6435787,0,43614,0;5,LA_T_1486451,0,50406,0;14,LA_T_1836557,0,43646,0;58,LA_T_4928920,0,64000,0;1,LA_D_1179848,1,29541,64000;24,LA_D_4519635,1,12487,64000;3,LA_D_1317561,1,8976,64000;7,LA_D_1803008,0,45707,0;56,LA_D_9316963,0,58699,0;0,LA_D_1179848,0,64000,0: 98;119;15;12;91;142;7;121;125;37;78;5;14;174;58;118
3,LA_T_1373588,0,46949,0, 1/134, Time: 0.331835s, Loss: 0.192797
87,LA_T_6960076,0,42296,0, 2/134, Time: 0.331835s, Loss: 0.192797
72,LA_T_5894355,0,64000,0, 3/134, Time: 0.331835s, Loss: 0.192797
62,LA_T_5209704,1,34511,64000, 4/134, Time: 0.331835s, Loss: 0.192797
46,LA_T_3588714,0,46298,0, 5/134, Time: 0.331835s, Loss: 0.192797
115,LA_T_9746209,0,64000,0, 6/134, Time: 0.331835s, Loss: 0.192797
15,LA_T_1870524,0,43190,0, 7/134, Time: 0.331835s, Loss: 0.192797
53,LA_T_4512109,0,51563,0, 8/134, Time: 0.331835s, Loss: 0.192797
29,LA_T_2422854,0,62661,0, 9/134, Time: 0.331835s, Loss: 0.192797
41,LA_T_3391018,0,57402,0, 10/134, Time: 0.331835s, Loss: 0.192797
```

**Comment by TonyWangX** [comment]
> I would like to ask how to use the pre-trained model in the downloaded folder project08-seed-model.tar to evaluate the wild data set?

I think you can follow the demo script here to execute the inference.
https://github.com/nii-yamagishilab/project-NN-Pytorch-scripts/blob/e269196d8bf3d3730bedc284b720e481ea7f16ca/project/08-asvspoof-activelearn/00_demo.sh#L104

I don't have clever ideas on how to make pre-trained models work in the wild. It is usually very challenging. 

Maybe you can fine-tune the model with some development set data from that domain?
