### ISSUE TITLE
About 10-asvspoof-vocoded-trn-ssl - xlsr_53_56k.pt

### ISSUE THREAD

**Issue by Ju-li-us** [nii-yamagishilab/project-NN-Pytorch-scripts#60]
Dear author,
I'm a big fan of this repository. But when I try to run the P1-Model I get the following error:
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    main()
  File "main.py", line 209, in main
    model = prj_model.Model(test_set.get_in_dim(), \
  File "/srv/storage/user/project-NN-Pytorch-scripts/project/10-asvspoof-vocoded-trn-ssl/model-ID-P1/trained-for-paper/01/model.py", line 483, in __init__
    self.m_front_end = FrontEnd(prj_conf.ssl_front_end_path,
  File "/srv/storage/user/project-NN-Pytorch-scripts/project/10-asvspoof-vocoded-trn-ssl/model-ID-P1/trained-for-paper/01/model.py", line 118, in __init__
    self.ssl_model = SSLModel(mpath, ssl_out_dim, ssl_layer_indices)
  File "/srv/storage/user/project-NN-Pytorch-scripts/project/10-asvspoof-vocoded-trn-ssl/model-ID-P1/trained-for-paper/01/model.py", line 49, in __init__
    self.model = S3PRLUpstream("wav2vec2_custom", path_or_url = mpath)
  File "/srv/storage/user/project-NN-Pytorch-scripts-master/project/10-asvspoof-vocoded-trn-ssl/s3prl/s3prl/nn/upstream.py", line 117, in __init__
    self.upstream = getattr(hub, name)(**upstream_conf)
  File "/srv/storage/user/project-NN-Pytorch-scripts-master/project/10-asvspoof-vocoded-trn-ssl/s3prl/s3prl/upstream/wav2vec2/hubconf.py", line 61, in wav2vec2_custom
    assert os.path.isfile(ckpt)
AssertionError

I think the reason for that is, that you forgot to include the download-procedure for the model xlsr_53_56k.pt in 01_download_pretrained_cm.sh.

Best regards,
Julius

**Comment by TonyWangX** [comment]
Thank you very much. Indeed!
